# Generated by Django 4.1.7 on 2023-03-26 17:08

import datetime
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50, verbose_name='Конторль')),
            ],
            options={
                'verbose_name': 'Контроль',
                'verbose_name_plural': 'Контроль',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50, verbose_name='Ваш участок')),
            ],
            options={
                'verbose_name': 'Ваш участок',
                'verbose_name_plural': 'Ваши участки',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=30, verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
            },
        ),
        migrations.CreateModel(
            name='View',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50, verbose_name='Вид')),
            ],
            options={
                'verbose_name': 'Вид',
                'verbose_name_plural': 'Виды',
            },
        ),
        migrations.CreateModel(
            name='StaffGroup',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50, verbose_name='Участок наблюдения')),
                ('sites_manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='observations.staffgroup', verbose_name='Руководитель участка')),
                ('sites_organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='observations.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Участок наблюдения',
                'verbose_name_plural': 'Участки наблюдения',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50, verbose_name='Место наблюдения')),
                ('place_organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='observations.organization', verbose_name='Организация')),
                ('site_place', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='observations.site', verbose_name='Участок наблюдения')),
            ],
            options={
                'verbose_name': 'Место наблюдения',
                'verbose_name_plural': 'Места наблюдения',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_viewed', models.DateField(default=datetime.date.today, verbose_name='Дата наблюдения')),
                ('character', models.CharField(choices=[('М-', 'Место(-) Условия труда не безопасные'), ('М+', 'Место(+) Условия труда безопасные'), ('П-', 'Поведение(-) Поведение не безопасное'), ('П+', 'Поведение(+) Поведение безопасное')], default='', max_length=35, verbose_name='Характер наблюдения')),
                ('dialog', models.BooleanField(blank=True, choices=[(True, 'Да'), (False, 'Нет')], verbose_name='Был диалог (да/нет)')),
                ('description', models.TextField(max_length=512, verbose_name='Описание')),
                ('probability', models.PositiveSmallIntegerField(default=0, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='Вероятность (от 0 до 5)')),
                ('effects', models.PositiveSmallIntegerField(default=0, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='Последствия (от 0 до 5)')),
                ('risk', models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Уровень риска')),
                ('correction', models.TextField(blank=True, max_length=256, verbose_name='Улучшение\\Влияние')),
                ('date_closed_target', models.DateField(verbose_name='Дата закрытия - цель')),
                ('date_closed_fact', models.DateField(blank=True, null=True, verbose_name='Дата закрытия - факт')),
                ('status', models.CharField(choices=[('New', 'Новое'), ('Progress', 'В работе'), ('Postponed', 'Отложено'), ('Rejected', 'Отклонено'), ('Completed', 'Выполнено')], default='New', max_length=15, verbose_name='Статус')),
                ('is_closed', models.BooleanField(choices=[(True, 'Закрыто'), (False, 'Открыто')], default=False, verbose_name='Состояние наблюдения')),
                ('date_created', models.DateField(default=datetime.date.today)),
                ('corr_action', models.TextField(blank=True, max_length=512, verbose_name='Корректирующие мероприятия')),
                ('photo1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='Фото1')),
                ('photo2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='Фото2')),
                ('photo3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='Фото3')),
                ('photo4', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='Фото4')),
                ('photo5', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='Фото5')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categories', to='observations.category', verbose_name='Категория')),
                ('control', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='controls', to='observations.control', verbose_name='Контроль')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='managers', to='observations.staffgroup', verbose_name='Руководитель')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owners', to='observations.staffgroup', verbose_name='Пользователь')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='places', to='observations.place', verbose_name='Участок наблюдения')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sites', to='observations.site', verbose_name='Участок наблюдения')),
                ('users_department', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users_department', to='observations.department', verbose_name='Ваш участок')),
                ('users_organization', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users_organization', to='observations.organization', verbose_name='Организация')),
                ('view', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='views', to='observations.view', verbose_name='Вид наблюдения')),
            ],
            options={
                'verbose_name': 'Наблюдение по безопасности',
                'verbose_name_plural': 'Наблюдения по безопасности',
                'ordering': ['date_created'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_manager', models.BooleanField(default=False, verbose_name='Является руководителем(да/нет)')),
                ('responsible_manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manager', to='observations.staffgroup', verbose_name='Ответственный руководитель')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='employee', to='observations.staffgroup', verbose_name='Имя сотрудника')),
                ('users_department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='observations.department', verbose_name='Ваш участок')),
                ('users_organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='observations.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['user'],
            },
        ),
    ]
