# Generated by Django 4.1.7 on 2023-03-26 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='places', to='observations.place', verbose_name='Место наблюдения'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sites', to='observations.department', verbose_name='Участок наблюдения'),
        ),
        migrations.AlterField(
            model_name='place',
            name='site_place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='observations.department', verbose_name='Участок наблюдения'),
        ),
        migrations.DeleteModel(
            name='Site',
        ),
    ]
