# Generated by Django 4.1.7 on 2023-03-26 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0002_alter_observation_place_alter_observation_site_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='observations.department', verbose_name='Участок наблюдения')),
                ('sites_manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='observations.staffgroup', verbose_name='Руководитель участка')),
                ('sites_organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='observations.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Участок наблюдения',
                'verbose_name_plural': 'Участки наблюдения',
                'ordering': ['name'],
            },
        ),
    ]
