# Generated by Django 4.1.7 on 2023-03-27 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0004_alter_observation_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sites', to='observations.site', verbose_name='Участок наблюдения'),
        ),
        migrations.AlterField(
            model_name='site',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='observations.department', verbose_name='Участок из ваш участок'),
        ),
    ]
