# Generated by Django 4.1.7 on 2023-04-16 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0008_alter_observation_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='observation',
            options={'ordering': ['-id'], 'verbose_name': 'Наблюдение по безопасности', 'verbose_name_plural': 'Наблюдения по безопасности'},
        ),
    ]
