# Generated by Django 4.1.7 on 2023-04-16 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0011_alter_observation_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='manager',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='managers', to='observations.employee', verbose_name='Руководитель'),
        ),
    ]
