# Generated by Django 4.1.7 on 2023-04-22 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0013_alter_observation_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='character',
            field=models.CharField(choices=[('М-', 'Место(-)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Условия труда не безопасные'), ('М+', 'Место(+)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Условия труда безопасные'), ('П-', 'Поведение(-)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Поведение не безопасное'), ('П+', 'Поведение(+)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Поведение безопасное')], default='', max_length=35, verbose_name='Характер наблюдения'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='managers', to='observations.employee', verbose_name='Ответственный руководитель'),
        ),
        migrations.AlterField(
            model_name='place',
            name='site_place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='observations.site', verbose_name='Участок наблюдения'),
        ),
    ]
